# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-05-29 07:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0003_remove_profile_images'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='imageuploader_profile',
            new_name='user',
        ),
        migrations.AddField(
            model_name='image',
            name='profile',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='images.Profile'),
            preserve_default=False,
        ),
    ]
